from pathlib import Path
import pandas as pd
import requests

# File generated by find_bhopal_tiles.py
MANIFEST_FILE = "bhopal_microsoft_tiles.csv"

# Download directory
OUTPUT_DIR = Path("data/raw/microsoft_bhopal")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(MANIFEST_FILE, dtype=str)

print(f"Tiles to download: {len(df)}")

for _, row in df.iterrows():
    quadkey = row["QuadKey"]
    url = row["Url"]

    output_file = OUTPUT_DIR / f"{quadkey}.csv.gz"

    print("\n" + "=" * 70)
    print(f"QuadKey : {quadkey}")
    print(f"Output  : {output_file}")
    print(f"URL     : {url}")

    if output_file.exists():
        print("Already downloaded. Skipping.")
        continue

    print("Downloading...")

    with requests.get(
        url,
        stream=True,
        timeout=300
    ) as response:

        response.raise_for_status()

        total = int(response.headers.get("content-length", 0))
        downloaded = 0

        with open(output_file, "wb") as f:
            for chunk in response.iter_content(
                chunk_size=1024 * 1024
            ):
                if not chunk:
                    continue

                f.write(chunk)
                downloaded += len(chunk)

                if total:
                    percent = downloaded * 100 / total
                    print(
                        f"\rProgress: {percent:6.2f}%",
                        end=""
                    )

    print("\nDownloaded successfully.")

print("\n" + "=" * 70)
print("ALL BHOPAL TILES DOWNLOADED")
print("=" * 70)
